[project]
name = "compare_bill_numbering"
version = "1.1.1"
license = { file = "LICENCE" }
dependencies = [
    "click",
    "lxml",
    "pandas",
    "python-dateutil",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["lxml-stubs"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# these are entry points for the command line
[project.scripts]
compare_bills = "compare_bill_numbering:cli"



